### ISSUE TITLE
TypeError: AttnProcessor2_0.__call__() got multiple values for argument 'encoder_hidden_states'

### ISSUE THREAD

**Issue by Revln9** [memoavatar/memo#6]
Hi, any idea what is this error about ?
I am on windows using cuda 12.4 and torch 2.5.1

Thanks

```
Generating video clips:   0%|                                                                     | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "H:\memo\memo\inference.py", line 251, in <module>
    main()
  File "H:\memo\memo\inference.py", line 227, in main
    pipeline_output = pipeline(
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "H:\memo\memo\memo\pipelines\video_pipeline.py", line 260, in __call__
    noise_pred = self.diffusion_net(
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\memo\memo\memo\models\unet_3d.py", line 484, in forward
    sample, res_samples, audio_embedding = downsample_block(
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\memo\memo\memo\models\unet_3d_blocks.py", line 562, in forward
    hidden_states = motion_module(
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\memo\memo\memo\models\motion_module.py", line 69, in forward
    hidden_states = self.temporal_transformer(
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\memo\memo\memo\models\motion_module.py", line 172, in forward
    hidden_states = block(
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\memo\memo\memo\models\motion_module.py", line 253, in forward
    attention_block(
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\anaconda3\envs\memo\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\memo\memo\memo\models\motion_module.py", line 371, in forward
    hidden_states = self.processor(
TypeError: AttnProcessor2_0.__call__() got multiple values for argument 'encoder_hidden_states'
```

**Comment by Revln9** [comment]
This line in the inference.yaml was causing the issue:
enable_xformers_memory_efficient_attention: false
I tried to disable so i don't have to install xformers, after installing xformers and enabling the issue has gone away.
Thans

**Comment by libhot** [comment]
my GPU version is too low ,must set   enable_xformers_memory_efficient_attention: false
and then get another error :
TypeError: AttnProcessor2_0.__call__() got multiple values for argument 'encoder_hidden_states'

**Comment by shirubei** [comment]
Same error even after set enable_xformers_memory_efficient_attention: false
2080Ti with torch 2.4.0+cu121

**Comment by shirubei** [comment]
> Same error even after set enable_xformers_memory_efficient_attention: false 2080Ti with torch 2.4.0+cu121

changed to torch 2.5.1+cu124, xformers 0.0.28.post3 and this error disappeared. 
Installing xformers from source failed but managed to get xformers wheel from https://download.pytorch.org/whl/xformers/ 
Now got OutOfMemory error.
