### ISSUE TITLE
I keep getting this config error and I have tried everything to  fix it

### ISSUE THREAD

**Issue by IntellectzProductions** [memoavatar/memo#7]
I hate to complain but usually I fix these errors. Today I just can't figure this out. I will paste the error as  I am lost as to what is going on. I don't know what config file it wants in the memo folder. There isn't a config file on the huggingface page where I downloaded all the models:
Traceback (most recent call last):
  File "E:\memo\memo\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
E:\memo\memo\lib\site-packages\transformers\utils\hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
E:\memo\memo\lib\site-packages\rotary_embedding_torch\rotary_embedding_torch.py:35: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
E:\memo\memo\lib\site-packages\rotary_embedding_torch\rotary_embedding_torch.py:268: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
INFO:memo:Loading config from configs/inference.yaml
INFO:memo:The MEMO model will be downloaded from Hugging Face to the default cache directory. The models for face analysis and vocal separation will be downloaded to checkpoints.
INFO:memo:Downloading 1k3d68.onnx to checkpoints\misc/face_analysis
'wget' is not recognized as an internal or external command,
operable program or batch file.
INFO:memo:Downloading 2d106det.onnx to checkpoints\misc/face_analysis
'wget' is not recognized as an internal or external command,
operable program or batch file.
INFO:memo:Downloading face_landmarker_v2_with_blendshapes.task to checkpoints\misc/face_analysis
'wget' is not recognized as an internal or external command,
operable program or batch file.
INFO:memo:Downloading genderage.onnx to checkpoints\misc/face_analysis
'wget' is not recognized as an internal or external command,
operable program or batch file.
INFO:memo:Downloading glintr100.onnx to checkpoints\misc/face_analysis
'wget' is not recognized as an internal or external command,
operable program or batch file.
INFO:memo:Downloading scrfd_10g_bnkps.onnx to checkpoints\misc/face_analysis
'wget' is not recognized as an internal or external command,
operable program or batch file.
INFO:memo:Use face analysis models from checkpoints\misc/face_analysis
INFO:memo:Vocal separator checkpoints\misc/vocal_separator/Kim_Vocal_2.onnx already exists. Skipping download.
INFO:memo:Inference dtype: torch.bfloat16
INFO:memo:Processing image ComfyUI_00025_.png
Using model directory: checkpoints\misc/face_analysis\models\
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
Loaded model: checkpoints\misc/face_analysis\models\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
Loaded model: checkpoints\misc/face_analysis\models\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
Loaded model: checkpoints\misc/face_analysis\models\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
Loaded model: checkpoints\misc/face_analysis\models\glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
Loaded model: checkpoints\misc/face_analysis\models\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
WARNING:py.warnings:E:\memo\memo\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4

INFO:memo:Processing audio fanvue_intro.wav
Some weights of Wav2VecModel were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:audio_separator.separator.separator:Separator version 0.24.1 instantiating with output_dir: outputs\audio_preprocess, output_format: WAV
INFO:audio_separator.separator.separator:Operating System: Windows 10.0.22631
INFO:audio_separator.separator.separator:System: Windows Node: DESKTOP-GI9R08D Release: 10 Machine: AMD64 Proc: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
INFO:audio_separator.separator.separator:Python Version: 3.10.1
INFO:audio_separator.separator.separator:PyTorch Version: 2.5.1+cu118
INFO:audio_separator.separator.separator:FFmpeg installed: ffmpeg version 2024-10-31-git-87068b9600-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
INFO:audio_separator.separator.separator:ONNX Runtime GPU package installed with version: 1.20.1
INFO:audio_separator.separator.separator:CUDA is available in Torch, setting Torch device to CUDA
INFO:audio_separator.separator.separator:ONNXruntime has CUDAExecutionProvider available, enabling acceleration
INFO:audio_separator.separator.separator:Loading model Kim_Vocal_2.onnx...
INFO:audio_separator.separator.separator:Load model duration: 00:00:00
INFO:audio_separator.separator.separator:Starting separation process for audio_file_path: outputs\audio_preprocess\fanvue_intro-16k.wav
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  3.72it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  9.26it/s]
INFO:audio_separator.separator.separator:Saving Vocals stem to fanvue_intro-16k_(Vocals)_Kim_Vocal_2.wav...
INFO:audio_separator.separator.separator:Audio duration is 0.00 hours (9.60 seconds).
INFO:audio_separator.separator.separator:Using pydub for writing.
INFO:audio_separator.separator.separator:Clearing input audio file paths, sources and stems...
INFO:audio_separator.separator.separator:Separation duration: 00:00:02
INFO:memo:Processing audio emotion
INFO:memo.utils.audio_utils:Downloading emotion2vec models from modelscope
Downloading Model to directory: C:\Users\GGINTELLECTZ\.cache\modelscope\hub\iic/emotion2vec_plus_large
2024-12-07 20:23:18,503 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
Detect model requirements, begin to install it: C:\Users\GGINTELLECTZ\.cache\modelscope\hub\iic\emotion2vec_plus_large\requirements.txt
install model requirements successfully
Traceback (most recent call last):
  File "E:\memo\inference.py", line 251, in <module>
    main()
  File "E:\memo\inference.py", line 135, in main
    audio_emotion, num_emotion_classes = extract_audio_emotion_labels(
  File "E:\memo\memo\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "E:\memo\memo\utils\audio_utils.py", line 189, in extract_audio_emotion_labels
    classifier = AudioEmotionClassifierModel.from_pretrained(
  File "E:\memo\memo\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\memo\memo\lib\site-packages\diffusers\models\modeling_utils.py", line 640, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "E:\memo\memo\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\memo\memo\lib\site-packages\diffusers\configuration_utils.py", line 373, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory memoavatar/memo.

**Comment by ltzheng** [comment]
It seems to be the issue of loading the emotion classifier. The config can be found [here](https://huggingface.co/memoavatar/memo/tree/main/misc/audio_emotion_classifier). This is weird because the default code should be able to download it automatically.

**Comment by ltzheng** [comment]
> 'wget' is not recognized as an internal or external command, operable program or batch file.

There is also no wget installed on your machine.

**Comment by nitinmukesh** [comment]
Even if wget is installed it doesn't work on Windows. I atleast get error downloading using wget.

**Comment by Mateleo** [comment]
I have exactly the same issue with Windows even with wget installed

**Comment by IntellectzProductions** [comment]
I don't want to jump the gun on this but, it seems something is missing for Windows users. Does this require s specific version of that model or config? I added a dummy config file and then it says the pytorch model itself is missing even though I have everything you have on huggingface set up folder for folder and file for file

**Comment by ltzheng** [comment]
I don't have a Windows machine right now, but I guess using Ubuntu with WSL would help.
